"""add_error_message_to_messages

Revision ID: 2f516ea3e0b8
Revises: a40cb7d2a49d
Create Date: 2026-04-14 13:23:02.070629
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2f516ea3e0b8'
down_revision: Union[str, None] = 'a40cb7d2a49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'error_message')
    # ### end Alembic commands ###
